# Generated by Django 5.2.8 on 2026-07-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceDate', models.DateField()),
                ('MealPeriod', models.CharField(max_length=32)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Status', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['ServiceDate', 'StartTime'],
            },
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNumber', models.CharField(max_length=16, unique=True)),
                ('Capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoyageCode', models.CharField(max_length=32, unique=True)),
                ('Status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartySize', models.PositiveIntegerField()),
                ('Status', models.CharField(max_length=32)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(blank=True)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TideTableDiningApp.diningsession')),
                ('Table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='TideTableDiningApp.diningtable')),
                ('Voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TideTableDiningApp.voyage')),
            ],
            options={
                'ordering': ['-CreatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingNumber', models.CharField(max_length=64)),
                ('PMSGuestID', models.CharField(max_length=64)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('CabinNumber', models.CharField(max_length=16)),
                ('Voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='TideTableDiningApp.voyage')),
            ],
        ),
        migrations.AddField(
            model_name='diningsession',
            name='Voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='TideTableDiningApp.voyage'),
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsLeadGuest', models.BooleanField(default=False)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='TideTableDiningApp.guest')),
                ('Reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_guests', to='TideTableDiningApp.reservation')),
            ],
            options={
                'unique_together': {('Reservation', 'Guest')},
            },
        ),
    ]
